# Generated by Django 2.2.6 on 2019-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='campaign',
        ),
        migrations.AddField(
            model_name='link',
            name='utm_campaign',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='link',
            name='utm_source',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='audience',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='brand',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='channel',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='deeplink_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='desktop_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='fallback_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='mvp_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='placement_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='placement_type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='link',
            name='vendor',
            field=models.CharField(default='', max_length=250),
        ),
    ]
